Feature hit judgements
happpy24/tosu-btmc-overlay pull request #14
Opened 2024-10-08 08:34 UTC by CaptSiro

Inside the function `createChartConfig` you can fiddle with colours of the graph.

Condition `index.js:241` probably needs a bit more tweaking but generally it should work

2024-10-08 08:45 UTC, AutumnVN commented on js/GraphFill.js
> +        this.#border = border ?? fill.clone().setAlpha(1);
dont use ?? it breaks ingame overlay
```suggestion
        this.#border = border !== undefined ? border : fill.clone().setAlpha(1);
```

2024-10-08 14:12 UTC, vifiiy commented on js/GraphFill.js
> +        this.#border = border ?? fill.clone().setAlpha(1);
true

2024-10-08 14:12 UTC, vifiiy requested changes
@CaptSiro Could you resolve the merge conflicts by merging with main and resolving them?

2024-10-08 18:53 UTC, CaptSiro commented on js/GraphFill.js
> +        this.#border = border ?? fill.clone().setAlpha(1);
I wonder how because `a ?? b` is just syntax sugar for `a === undefined ? b : a`

2024-10-08 18:55 UTC, happpy24 commented on js/GraphFill.js
> +        this.#border = border ?? fill.clone().setAlpha(1);
tosu's typescript doesnt really like it

2024-10-08 19:00 UTC, brw commented on js/GraphFill.js
> +        this.#border = border ?? fill.clone().setAlpha(1);
Null-ish coalescing operator was added in ES2020. Perhaps whatever JS engine tosu uses for its ingame overlay is just an older version.

2024-10-09 11:44 UTC, happpy24 approved these changes
lgtm!

2024-10-09 11:44 UTC, merged